// Component-owned copy; shared locale dictionaries remain unchanged.
const messages = {
  en: {
    comparison_zeroBoth: 'Today so far and the previous daily baseline are both zero. This comparison is provisional.',
    dailyError: 'Daily energy history could not be loaded.',
    todayConsumption: 'Consumption today so far: {amount} kWh',
    averageConsumption: 'Previous 7-day average: {amount} kWh/day',
    baselineCoverage: 'Consumption data: {days} of the previous 7 completed days. Missing days are excluded.',
    comparison_higher: 'Today so far is {percent}% above the previous daily average. This comparison is provisional.',
    comparison_lower: 'Today so far is {percent}% below the previous daily average. This comparison is provisional.',
    comparison_inLine: 'Today so far is within 10% of the previous daily average. This comparison is provisional.',
    comparison_aboveZero: 'Today so far is {amount} kWh above a zero daily baseline. This comparison is provisional.',
    comparisonUnavailable: 'A comparison needs a valid reading for today and at least one previous completed day.',
    trend_increasing: 'Consumption increased across the last 3 completed days.',
    trend_decreasing: 'Consumption decreased across the last 3 completed days.',
    impactCoverage: 'This month: generation data for {generationDays} of {days} days; matched production/consumption for {matchedDays} days.',
    solarMissing: 'Solar metrics need valid readings within this period. Coverage also needs positive consumption.',
    snapshotNote: 'Daily values use the latest reading for each Asia/Colombo day. Today is so far; missing days are not zero.',
    coverageEstimateNote: 'Estimated solar coverage caps each day’s generation at its consumption. It does not measure actual solar use or battery flows.',
    historyError: 'Transaction history could not be refreshed. Check your connection and try again.',
    historyStale: 'Showing previously loaded history and totals. They may be out of date.',
    signIn: 'Sign in to view your energy activity.',
    loading: 'Loading your energy readings…',
    noRecords: 'No energy readings are available for your account.',
    energyError: 'Energy readings could not be loaded.',
    ledgerError: 'Shared energy could not be loaded.',
    latest: 'Latest reading: {date} (Asia/Colombo).',
    stale: 'No reading for today.',
    future: 'Reading date is in the future.',
    dailyUnavailable: 'Daily consumption insights are unavailable. These readings do not yet support verified daily totals.',
    available: 'Available to share: {amount} kWh, based on your current trade balance.',
    insightsNote: 'Daily averages and trends will appear when supported by your energy data.',
    period: 'Month to date: {start} to {end} (Asia/Colombo)',
    coverage: 'Estimated solar coverage',
    solarUnavailable: 'Solar generation and estimated solar coverage are unavailable until daily energy totals can be verified.',
    sharingNote: 'Shared energy includes only your completed outgoing trades during this period.',
  },
  si: {
    comparison_zeroBoth: 'අද මේ දක්වා පරිභෝජනය සහ පෙර දෛනික පදනම දෙකම ශුන්‍යය. මෙය තාවකාලික සැසඳීමකි.',
    dailyError: 'දෛනික බලශක්ති ඉතිහාසය පූරණය කළ නොහැකි විය.',
    todayConsumption: 'අද මේ දක්වා පරිභෝජනය: {amount} kWh',
    averageConsumption: 'පසුගිය දින 7 සාමාන්‍යය: {amount} kWh/දින',
    baselineCoverage: 'පසුගිය සම්පූර්ණ දින 7න් දින {days}ක පරිභෝජන දත්ත ඇත. දත්ත නොමැති දින බැහැර කර ඇත.',
    comparison_higher: 'අද මේ දක්වා පරිභෝජනය පෙර දෛනික සාමාන්‍යයට වඩා {percent}% වැඩිය. මෙය තාවකාලික සැසඳීමකි.',
    comparison_lower: 'අද මේ දක්වා පරිභෝජනය පෙර දෛනික සාමාන්‍යයට වඩා {percent}% අඩුය. මෙය තාවකාලික සැසඳීමකි.',
    comparison_inLine: 'අද මේ දක්වා පරිභෝජනය පෙර දෛනික සාමාන්‍යයේ 10% සීමාව තුළ ඇත. මෙය තාවකාලික සැසඳීමකි.',
    comparison_aboveZero: 'අද මේ දක්වා පරිභෝජනය ශුන්‍ය දෛනික පදනමට වඩා {amount} kWh වැඩිය. මෙය තාවකාලික සැසඳීමකි.',
    comparisonUnavailable: 'සැසඳීමට අද සඳහා වලංගු කියවීමක් සහ අවම වශයෙන් පෙර සම්පූර්ණ දිනක දත්ත අවශ්‍යය.',
    trend_increasing: 'පසුගිය සම්පූර්ණ දින 3 තුළ පරිභෝජනය වැඩි විය.',
    trend_decreasing: 'පසුගිය සම්පූර්ණ දින 3 තුළ පරිභෝජනය අඩු විය.',
    impactCoverage: 'මෙම මාසයේ දින {days}න් දින {generationDays}ක ජනන දත්ත ඇත; දින {matchedDays}ක ජනන සහ පරිභෝජන දත්ත ගැලපේ.',
    solarMissing: 'සූර්ය දර්ශක සඳහා මෙම කාලය තුළ වලංගු කියවීම් අවශ්‍යය. ආවරණය සඳහා ධන පරිභෝජනයද අවශ්‍යය.',
    snapshotNote: 'දෛනික අගයන් සඳහා එක් එක් Asia/Colombo දිනයේ නවතම කියවීම භාවිත වේ. අද අගය මේ දක්වා පමණි; දත්ත නොමැති දින ශුන්‍ය නොවේ.',
    coverageEstimateNote: 'ඇස්තමේන්තුගත සූර්ය ආවරණය එක් එක් දිනයේ ජනනය එදින පරිභෝජනයට සීමා කරයි. එය සැබෑ සූර්ය භාවිතය හෝ බැටරි ප්‍රවාහ මනින්නේ නැත.',
    historyError: 'ගනුදෙනු ඉතිහාසය යාවත්කාලීන කළ නොහැකි විය. ඔබේ සම්බන්ධතාව පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
    historyStale: 'කලින් පූරණය කළ ඉතිහාසය සහ එකතුව පෙන්වයි. ඒවා යාවත්කාලීන නොවිය හැක.',
    signIn: 'ඔබේ බලශක්ති ක්‍රියාකාරකම් බැලීමට පිවිසෙන්න.',
    loading: 'ඔබේ බලශක්ති කියවීම් පූරණය වෙමින් පවතී…',
    noRecords: 'ඔබේ ගිණුම සඳහා බලශක්ති කියවීම් නොමැත.',
    energyError: 'බලශක්ති කියවීම් පූරණය කළ නොහැකි විය.',
    ledgerError: 'බෙදාගත් බලශක්ති දත්ත පූරණය කළ නොහැකි විය.',
    latest: 'නවතම කියවීම: {date} (Asia/Colombo).',
    stale: 'අද සඳහා කියවීමක් නොමැත.',
    future: 'කියවීමේ දිනය අනාගත දිනයකි.',
    dailyUnavailable: 'දෛනික පරිභෝජන විශ්ලේෂණය ලබාගත නොහැක. මෙම කියවීම් මගින් තහවුරු කළ දෛනික එකතුවක් තවම ලබාගත නොහැක.',
    available: 'වත්මන් වෙළඳ ශේෂය අනුව බෙදාගත හැකි බලශක්තිය: {amount} kWh.',
    insightsNote: 'ඔබේ බලශක්ති දත්ත සහාය දක්වන විට දෛනික සාමාන්‍ය සහ ප්‍රවණතා පෙන්වනු ඇත.',
    period: 'මෙම මාසයේ මේ දක්වා: {start} සිට {end} දක්වා (Asia/Colombo)',
    coverage: 'ඇස්තමේන්තුගත සූර්ය බලශක්ති ආවරණය',
    solarUnavailable: 'දෛනික බලශක්ති එකතුව තහවුරු කරන තෙක් සූර්ය බලශක්ති ජනනය සහ ඇස්තමේන්තුගත සූර්ය ආවරණය ලබාගත නොහැක.',
    sharingNote: 'බෙදාගත් බලශක්තියට ඇතුළත් වන්නේ මෙම කාලය තුළ ඔබ විසින් යවන ලද සම්පූර්ණ කළ වෙළඳ ගනුදෙනු පමණි.',
  },
  ta: {
    comparison_zeroBoth: 'இன்று இதுவரையிலான நுகர்வும் முந்தைய தினசரி அடிப்படையும் பூஜ்ஜியம். இது தற்காலிக ஒப்பீடு.',
    dailyError: 'தினசரி ஆற்றல் வரலாற்றை ஏற்ற முடியவில்லை.',
    todayConsumption: 'இன்று இதுவரையிலான நுகர்வு: {amount} kWh',
    averageConsumption: 'முந்தைய 7 நாள் சராசரி: {amount} kWh/நாள்',
    baselineCoverage: 'முந்தைய 7 முடிவடைந்த நாட்களில் {days} நாட்களுக்கு நுகர்வு தரவு உள்ளது. தரவு இல்லாத நாட்கள் விலக்கப்பட்டுள்ளன.',
    comparison_higher: 'இன்று இதுவரை நுகர்வு முந்தைய தினசரி சராசரியை விட {percent}% அதிகம். இது தற்காலிக ஒப்பீடு.',
    comparison_lower: 'இன்று இதுவரை நுகர்வு முந்தைய தினசரி சராசரியை விட {percent}% குறைவு. இது தற்காலிக ஒப்பீடு.',
    comparison_inLine: 'இன்று இதுவரை நுகர்வு முந்தைய தினசரி சராசரியின் 10% வரம்பிற்குள் உள்ளது. இது தற்காலிக ஒப்பீடு.',
    comparison_aboveZero: 'இன்று இதுவரை நுகர்வு பூஜ்ஜிய தினசரி அடிப்படையை விட {amount} kWh அதிகம். இது தற்காலிக ஒப்பீடு.',
    comparisonUnavailable: 'ஒப்பீட்டிற்கு இன்றைய செல்லுபடியான அளவீடும் குறைந்தது ஒரு முந்தைய முடிவடைந்த நாளின் தரவும் தேவை.',
    trend_increasing: 'கடந்த 3 முடிவடைந்த நாட்களில் நுகர்வு அதிகரித்தது.',
    trend_decreasing: 'கடந்த 3 முடிவடைந்த நாட்களில் நுகர்வு குறைந்தது.',
    impactCoverage: 'இந்த மாதத்தின் {days} நாட்களில் {generationDays} நாட்களுக்கு உற்பத்தித் தரவு; {matchedDays} நாட்களுக்கு பொருந்தும் உற்பத்தி/நுகர்வு தரவு உள்ளது.',
    solarMissing: 'சூரிய அளவுகளுக்கு இந்தக் காலத்தின் செல்லுபடியான அளவீடுகள் தேவை. பங்கு கணக்கீட்டிற்கு நேர்மறை நுகர்வும் தேவை.',
    snapshotNote: 'ஒவ்வொரு Asia/Colombo நாளின் சமீபத்திய அளவீடு தினசரி மதிப்பாகப் பயன்படுத்தப்படுகிறது. இன்று இதுவரை மட்டுமே; தரவு இல்லாத நாட்கள் பூஜ்ஜியம் அல்ல.',
    coverageEstimateNote: 'மதிப்பிடப்பட்ட சூரிய ஆற்றல் பங்கு ஒவ்வொரு நாளின் உற்பத்தியையும் அன்றைய நுகர்விற்குள் வரையறுக்கிறது. இது உண்மையான சூரிய பயன்பாடு அல்லது பேட்டரி ஓட்டங்களை அளவிடாது.',
    historyError: 'பரிவர்த்தனை வரலாற்றைப் புதுப்பிக்க முடியவில்லை. உங்கள் இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    historyStale: 'முன்பு ஏற்றப்பட்ட வரலாறும் மொத்தங்களும் காட்டப்படுகின்றன. அவை தற்போதைய தரவாக இல்லாமல் இருக்கலாம்.',
    signIn: 'உங்கள் ஆற்றல் செயல்பாட்டைப் பார்க்க உள்நுழையவும்.',
    loading: 'உங்கள் ஆற்றல் அளவீடுகள் ஏற்றப்படுகின்றன…',
    noRecords: 'உங்கள் கணக்கிற்கான ஆற்றல் அளவீடுகள் இல்லை.',
    energyError: 'ஆற்றல் அளவீடுகளை ஏற்ற முடியவில்லை.',
    ledgerError: 'பகிரப்பட்ட ஆற்றல் தரவை ஏற்ற முடியவில்லை.',
    latest: 'சமீபத்திய அளவீடு: {date} (Asia/Colombo).',
    stale: 'இன்றைய அளவீடு இல்லை.',
    future: 'அளவீட்டின் தேதி எதிர்காலத்தில் உள்ளது.',
    dailyUnavailable: 'தினசரி நுகர்வு பகுப்பாய்வு கிடைக்கவில்லை. இந்த அளவீடுகளிலிருந்து சரிபார்க்கப்பட்ட தினசரி மொத்தங்களை இன்னும் பெற முடியவில்லை.',
    available: 'தற்போதைய வர்த்தக இருப்பின்படி பகிரக்கூடிய ஆற்றல்: {amount} kWh.',
    insightsNote: 'உங்கள் ஆற்றல் தரவு ஆதரிக்கும் போது தினசரி சராசரிகளும் போக்குகளும் காட்டப்படும்.',
    period: 'இந்த மாதத்தில் இதுவரை: {start} முதல் {end} வரை (Asia/Colombo)',
    coverage: 'மதிப்பிடப்பட்ட சூரிய ஆற்றல் பங்கு',
    solarUnavailable: 'தினசரி ஆற்றல் மொத்தங்கள் சரிபார்க்கப்படும் வரை சூரிய ஆற்றல் உற்பத்தியும் மதிப்பிடப்பட்ட சூரிய ஆற்றல் பங்கும் கிடைக்காது.',
    sharingNote: 'இந்தக் காலத்தில் நீங்கள் அனுப்பிய நிறைவடைந்த வர்த்தகங்களின் ஆற்றல் மட்டுமே பகிரப்பட்ட ஆற்றலில் சேர்க்கப்படும்.',
  },
};

export function analyticsText(language, key, values = {}) {
  const locale = String(language || 'en').toLowerCase().split(/[-_]/)[0];
  const template = messages[locale]?.[key] ?? messages.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (match, name) => values[name] == null ? match : String(values[name]));
}
